- name: httpd-installation
  hosts: workers
  remote_user: root
  become: true

  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: latest
    - name: Start nginx Service
      service:
        name: nginx
        state: started
    - name: Create html
      copy:
        content: "Welcome to Anisble!!"
        dest: /var/www/html/index.html  
    - name: print message
      debug: 
        msg: hello ansible world
    - name: create dir and file
      find:
        path: /satish
        file_type: file
    - name: ansible create directory example
      file:
        path: /satish
        state: directory
