- name: httpd-installation
  hosts: demo1
  remote_user: root
  become: true

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: Start httpd Service
      service:
        name: httpd
        state: started
    - name: Create html
      copy:
        content: "Welcome to Anisble!!"
        dest: /var/www/html/index.html  
    - name: print message
      debug: 
        msg: hello ansible world
    - name: create dir and file
      find:
        path: /root
        file_type: file
