apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myapp
  namespace: nginx-ingress  #Namespace gone be same as service and pod!
spec:
  rules:
  - host: myapp.com  # valid domain address and map domain name to Node's IP address, which is the entrypoint,must be mapped in /etc/hosts directory .
# - host: calander.myapp.com     #we can create sub-domains!(instead of above one to call direct demoservice. but one imp thing noticed individual path not be provide. )   
    http:
        paths:
      # - path: /democalander 
        - backend:
             serviceName: demoservice   # No nodePort in internal service, Instead of loadbalancer default type: ClusterIP
             servicePort: 80
      # - path: /shopping 
      #   backend:
      #      serviceName: shopping-service   # No nodePort in internal service, Instead of loadbalancer default type: ClusterIP
      #      servicePort: 3000
       
