kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: testpod
  annotations:
      description: "creating first pod for ubuntu image and write hello-satish in ubuntu container."
spec:                                    
  containers:                      
    - name: c00                     
      image: ubuntu              
      command: ["/bin/bash", "-c", "while true; do echo Hello-Satish; sleep 5 ; done"]
  restartPolicy: Never         # Defaults to Always
  #after saving this file run this command "kubectl apply -f pod_creation.yaml"
