apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-tls
  namespace: default       #Secret component must be in the same namespace as the ingress component.
data:
  tls.crt: base64 encoded cert         # Values are file contents Not file paths/location
  tls.key: base64 encoded key
type: kubernetes.io/tls
