---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: marveldeploy
spec:
   replicas: 2
   selector:     
    matchLabels:
     name: deployment
   template:
     metadata:
       name: marvelpod
       labels:
         name: deployment
     spec:
      containers:
        - name: marvelapp
          image: ditissdocker/myappk8s:tagVersion
          ports:
            - containerPort: 8080
              
---
kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: marvelservice
spec:
  ports:
    - protocol: TCP
      port: 80                               # Containers port exposed
      targetPort: 8080                     # Pods port
  selector:
    name: deployment                    # Apply this service to any pods which has the specific label
  type: LoadBalancer                       # Specifies the service type i.e ClusterIP or NodePort
          
